name: prueba
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.2
  local_auth: ^2.1.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/user1.jpg
    - assets/images/user2.jpg
    - assets/images/user3.jpg
    - assets/images/user4.jpg